%%初始化选取样本及样本函数y=x.^3+4
close all;clear all;
x=linspace(0,100,100);%选取样本横坐标
y=x.^3+4;%实际的函数值
%%拟合曲线为yfit=a*xfit+b
n=100;
x2=sum(x.^2);
x1=sum(x);
xy=sum(x.*y);
y1=sum(y);
a=(n*xy-xy)/(n*x2-x1*x1);
b=(y1-a*x1)/n;
xfit=linspace(0,100,999);%拟合曲线选取点
yfit=a*xfit+b;%拟合的一次函数
plot(xfit,yfit,x,y);%画图
e=a*xfit+b-xfit.^3-4;%误差公式
e2=sum(e.^2);%误差平方和
%%输出参数及误差,若e2过大则说明该区间一次拟合效果不好
a,b,e2